npmsw-test: delete temporarily
* fails to parse again after recent bitbake npmsw changes:

WARNING: /OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc                                                                                                                   | ETA:  --:--:--
WARNING: /OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test.bb: Error during finalise of /OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test.bb
ERROR: ExpansionError during parsing /OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test.bb
Traceback (most recent call last):
  File "/OE/build/luneos-styhead/bitbake/lib/bb/fetch2/__init__.py", line 1794, in Fetch.__init__(urls=['file://npm-local-link-sources/', 'npmsw:///OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test/npm-local-link-sources/inner/npm-shrinkwrap-v3.json'], d=<bb.
data_smart.DataSmart object at 0x7f0eb6e8c4a0>, cache=True, localonly=False, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                         self.ud[url].unpack_tracer = unpack_tracer
  File "/OE/build/luneos-styhead/bitbake/lib/bb/fetch2/__init__.py", line 1346, in FetchData.__init__(url='npmsw:///OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test/npm-local-link-sources/inner/npm-shrinkwrap-v3.json', d=<bb.data_smart.DataSmart object at 0x
7f0eb6e8c4a0>, localonly=False):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)

  File "/OE/build/luneos-styhead/bitbake/lib/bb/fetch2/npmsw.py", line 221, in NpmShrinkWrap.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f0eb6ea3c80>, d=<bb.data_smart.DataSmart object at 0x7f0eb6e8c4a0>):

    >        foreach_dependencies(shrinkwrap, _resolve_dependency, ud.dev)

  File "/OE/build/luneos-styhead/bitbake/lib/bb/fetch2/npmsw.py", line 69, in foreach_dependencies(shrinkwrap={'name': '@npm-local-link-sources/inner', 'version': '1.0.0', 'lockfileVersion': 3, 'requires': True, 'packages': {'': {'name': '@npm-local-link-sources/inner', 'version': '1.0.0', 'de
pendencies': {'@npm-local-link-sources/upper': 'file:../'}}, '..': {'name': '@npm-local-link-sources/upper', 'version': '1.0.0'}, 'node_modules/@npm-local-link-sources/upper': {'resolved': '..', 'link': True}}}, callback=<function NpmShrinkWrap.urldata_init.<locals>._resolve_dependency at 0x7f
0eb6e0a5c0>, dev=False):
                         continue
    >                callback(name, package_infos, package)
         else:
  File "/OE/build/luneos-styhead/bitbake/lib/bb/fetch2/npmsw.py", line 203, in _resolve_dependency(name='@npm-local-link-sources/upper', params={'resolved': '..', 'link': True}, destsuffix='node_modules/@npm-local-link-sources/upper'):
                 else:
    >                raise ParameterError("Unsupported dependency: name '%s', depname '%s', version '%s', resolved '%s'" % (name, depname, version, resolved), ud.url)

bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception ParameterError: URL: 'npmsw:///OE/build/luneos-styhead/meta-openembedded/meta-oe/recipes-devtools/nodejs/npmsw-test/npm-local-l
ink-sources/inner/npm-shrinkwrap-v3.json' has invalid parameters. Unsupported dependency: name '@npm-local-link-sources/upper', depname 'None', version '..', resolved '..'
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above

Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>